feat: Create dialog
watso-splitfare/watso_v2_ios pull request #2
Opened 2024-03-26 06:06 UTC by qordnjfdus

1. row 내 오른쪽 정렬 > crossAxisAlignment로 정렬은 됐으나, column 영역이 max로 설정이 안됨
2. column 내 왼쪽 정렬 > 마찬가지로 crossAxisAlignment 사용했으나, 적용안됨

* 일단 하드코딩으로 데이터 작성해둠
* 추가로 궁금한 점, 플러터로 ios와 android 를 작성하면 어떻게 다른지..? 근본적인 구조에 대한 궁금증

2024-03-26 06:55 UTC, charmeee commented
1,2번은 코드리뷰로 남겨놧어.

일단 하드코딩으로 데이터 작성해둠
- > 이 부분에서는 더미 데이터를 변수에 넣고 그걸 가져다 쓰는 형식으로 작성하면 나중에 통신할때 ui부분에서 건들게 적을것같아.

추가로 궁금한 점, 플러터로 ios와 android 를 작성하면 어떻게 다른지..? 근본적인 구조에 대한 궁금증
- > lib밑에있는 파일에서 작성한코드를 flutter프레임워크에서 ios와 android에서 같게 보이고 동작하도록 그들의 언어로 빌드해줘. 근데 와이파이설정이나 카메라나 네이티브한 영역을 다룰때는 ios폴더와 android폴더에 있는 네이티브코드 (swift, kotlin)을 직접 수정해야하는 경우도 있어.
flutter에서는 ui라이브러리는 기본적으로 안드로이드 모양을 하고있어.
import 'package:flutter/material.dart'; << 이게 그 안드로이드 모양 ui를 사용하는 라이브러리를 import한거야.
그래서 ios에서도 약간 안드로이드스럽게 앱이 보이기도하지. 그래서 flutter에서는 cupertino라고 ios ui도 지원을해
그래서 ui를 각각 os에 맞게 분기처리해서 개발할 수도 있지.

2024-03-26 06:56 UTC, charmeee commented
해당프로젝트에서 실행할 수 있도록 router에 페이지를 추가하고 main함수부부분을 지워주면 좋을 것같아.

2024-03-26 07:06 UTC, charmeee requested changes

2024-03-26 07:06 UTC, charmeee commented on dialog
> +                  ),
1. 현재 코드에서 오른쪽 정렬이 안되는 이유는 
Column 기본적으로는 넓이를 자식의 위젯의 넓이 만큼만 가져. 높이는 최대로 가지지. 마찬가지로 Row에서는 높이를 자식높이만큼가지고 넓이는 최대로 가져. 
그니까 현재 상황에서는 자식입장에서는  넓이가 자기넓이 만큼이니 왼쪽으로 가고말고 할게없는거지. 이걸해결하려면 상위 위젯에서 크기를 설정하고 Expand나  crossAxisAlignment에서 strech를 쓰면 채울 수 있는 공간 전부를 확장해서 넓이를 확보하고 정렬을 쓸 수 있어.

2. 저런 리스트형태의 위젯은 Row에서 mainAxisAlignment를 통해 한번에 정렬이 가능해 . 그리고 내생각에는 관련된 데이터를 같게 묶는 편이 개발할때도 편리하고 읽기도 좋은것 같거든? 
그래서 지금형태인 Row -> colomn을 통해 속성 데이터를 분리해서 하는것보다 column -> row를 통해서 속성과 해당속성의 데이터가 같이 있는게 더 좋을것같아. 그리고 이게 디자인이 반복된다 싶으면 Row로 된 타일을 분리해서 쓰는 것도 좋을것같고.

2024-03-26 07:06 UTC, charmeee commented on dialog
> +                    mainAxisSize: MainAxisSize.max,
이게 디폴트 속성이라 필요없는 코드일것같아

2024-03-26 07:06 UTC, charmeee approved these changes

2024-03-27 13:02 UTC, qordnjfdus commented
싹 갈아엎고, dialog 클래스 대신 alterDialog 사용했습니다. >> dialog 파일 X / main.dart+widgets.dart O

padding, row를 너무 남용하는 건 아닌지 궁금합니다!
더미 데이터를 변수에 넣어서 해보았는데 이런 식으로 하면 되는 걸까요? 추가로 필요한 것이 있어보이면 말해주세용
pr이 제대로 올라가고 있는 건가요? (양식이나 들어가야하는 파일 등)

2024-03-28 10:06 UTC, charmeee commented
lib안에 코드를 적어야해. 그래서 파일을 lib안에 넣어줫으면좋겟어
내생각엔 lib> taxi 밑에 widgets 라는폴더를 파고 dialog 파일을 widgets대신 receipt_dialog로 바꿔서 widgets폴더안에 넣으면 좋을 것같아.
위에 내가 잘못적엇는데 정산하기버튼이아니라 탑승자확정하기 버튼이더라고 ^^;;; 미안,,,,
그 탑승자확정하기 버튼이 내 코드에 있어 messaging_screen 안에 탑승자 확정하기 버튼을 누르면 ReceiptDialog가 뜨도록 바꿔줘

1. padding은 사실 많이써도상관없어. row도 필요해서 쓰는거지 딱히 과하지는 않은 거 같아.
2. 굳굳 잘해씀여.
3. 잘하고 잇음.
4. 기본적으로 flutter widget 디폴트 값이 완전하얀색이 아니더라. 완전 하얗지않은게 더튀는 느낌이 없긴하더라고. 다른앱에서도 많이 그렇게하고.  
alertdialog 위젯에서 backgroundcolor를 바꿔야돼.  만약 그렇게 해도 안됏으면 내가 나중에 테스트해볼게.
---
이건 내가 너한테 하고 싶은 질문이야! 
1. alert dialog를 사용한 이유가 있을까?
2. SingleChildScrollView를 사용한 이유가 있을까?

2024-03-28 12:42 UTC, qordnjfdus commented
1. https://developer.android.com/develop/ui/views/components/dialogs?hl=ko 
자료를 찾아보다가 위 링크에서 dialog를 직접 인스턴스화 하는 것보다 alertdialog 등을 사용하는 것을 권장한다는 문서를 보고 변경했습니다!
2. 혹시 내용이 길어지거나 화면을 가로로 했을 경우 스크롤을 위한 위젯이였습니다.
3. 개인당 요금이나 인원수 등에 변화가 있을 것을 생각해서 stateful 위젯으로 진행하였는데, 제가 잘못 알고 있는 부분일까요?

lib 파일 아래로 옮기고, messasing_screen에서 버튼 누르면 뜨도록 변경해뒀습니다! 근데 제 파일에선 watso/watso_v2_ios/lib 로 들어가서 제대로 됐는지 확인을 어떻게 해야될지 모르겠는데 뭔가 방법이 있을까요? 실행하면 watso/lib의 파일이 실행되서요!! (그래서 제대로 파일 위치, 이름이 변경된건지도 몰겠음요..)

2024-03-29 05:57 UTC, charmeee commented
1. 일단 저건 코틀린으로 안드로이드 개발할때 이야기이기도 하고
코틀린으로 개발할때 알림형태의 dialog는 alertdialog를 쓰는게 맞아. 근데 복잡한 dialog일시 직접 인스턴스화 하는게 아니라 dialog를 상속해서 customdialog를 만들어서 하더라고.
flutter에서도 비슷하게 사용하는거같아 간단한 알림,경고형태의 dialog는 alertdialog 그렇지 않은형태는 dialog를사용하는거 같아(flutter에서는 직접인스턴스하라는말은 없는거같아.) 내생각은 이 dialog가 간단한 알림,경고형태의 형태를 띄지않는것같고 좀더 복잡해보여서 Alert를 사용해도 상관없지만 dialog를 사용하는게 더 맞지않나 싶엇어
https://stackoverflow.com/questions/53349338/what-is-the-difference-between-dialog-and-alertdialog
2. 오 그거까지 고려하다니! 멋져
3. 지금형태가 widget밖에서 요금이나 인원수를 받는형태인거같더라고? statefulwidget은 위젯 생명주기동안에 데이터가 변형이 됐을때 그 데이터가 ui에 반영되어야할때 이용해. 지금 코드에서는 해당 위젯의 데이터를 외부에서 받고 난 후의 데이터의 변경은 없어보여. 이럴때는 statelesswidget을 쓰는게 좋아!


---
그 뒤에 부분은 내가 이해를 못햇어. 주말에 12-5시 사이에 톡주면 화면 보여주면서 알려주면 내가 해결해줄게!

2024-03-31 14:13 UTC, merged